import Header from "@/components/layout/header";
import Link from "next/link";

export default function PrivacyPolicy() {
  return (
    <div>
      <Header />

      <main className="px-[6rem] pt-[4.5rem] w-full flex flex-col gap-[4.5rem]">
        <div className="px-4 py-8 max-w-4xl mx-auto">
          <header className="mb-8">
            <h1 className="text-3xl font-bold text-center mb-4">
              Privacy Policy for Brilliant Travel
            </h1>
            <p className="text-center text-gray-500">
              Last updated: April 17, 2025
            </p>
          </header>

          <section className="space-y-6 text-justify">
            <p>
              This Privacy Policy describes Our policies and procedures on the
              collection, use and disclosure of Your information when You use
              the Service and tells You about Your privacy rights and how the
              law protects You.
            </p>
            <p>
              We use Your Personal data to provide and improve the Service. By
              using the Service, You agree to the collection and use of
              information in accordance with this Privacy Policy.
            </p>

            <h2 className="text-2xl font-semibold">
              Interpretation and Definitions
            </h2>
            <h3 className="text-xl font-semibold">Interpretation</h3>
            <p>
              The words of which the initial letter is capitalized have meanings
              defined under the following conditions. The following definitions
              shall have the same meaning regardless of whether they appear in
              singular or in plural.
            </p>

            <h3 className="text-xl font-semibold">Definitions</h3>
            <p>For the purposes of this Privacy Policy:</p>
            <ul className="list-disc pl-6 space-y-2">
              <li>
                <strong>Account</strong> means a unique account created for You
                to access our Service or parts of our Service.
              </li>
              <li>
                <strong>Affiliate</strong> means an entity that controls, is
                controlled by or is under common control with a party...
              </li>
              <li>
                <strong>Company</strong> refers to Brilliant Travel LLC, Baku.
              </li>
              <li>
                <strong>Cookies</strong> are small files that are placed on Your
                computer or device by a website...
              </li>
              <li>
                <strong>Country</strong> refers to: Azerbaijan
              </li>
              <li>
                <strong>Device</strong> means any device that can access the
                Service such as a computer, cellphone or tablet.
              </li>
              <li>
                <strong>Personal Data</strong> is any information that relates
                to an identified or identifiable individual.
              </li>
              <li>
                <strong>Service</strong> refers to the Website.
              </li>
              <li>
                <strong>Service Provider</strong> means any person who processes
                the data on behalf of the Company.
              </li>
              <li>
                <strong>Usage Data</strong> refers to data collected
                automatically, either generated by the use of the Service or
                from the Service infrastructure itself.
              </li>
              <li>
                <strong>Website</strong> refers to Brilliant Travel, accessible
                from{" "}
                <a
                  href="https://www.brillianttravel.info/"
                  target="_blank"
                  rel="noopener noreferrer"
                  className="text-blue-600 underline"
                >
                  https://www.brillianttravel.info/
                </a>
              </li>
              <li>
                <strong>You</strong> means the individual accessing or using the
                Service, or the company on whose behalf such individual is
                accessing or using the Service.
              </li>
            </ul>

            <h2 className="text-2xl font-semibold">
              Collecting and Using Your Personal Data
            </h2>
            <h3 className="text-xl font-semibold">Types of Data Collected</h3>
            <h4 className="text-lg font-semibold">Personal Data</h4>
            <p>
              While using Our Service, We may ask You to provide Us with certain
              personally identifiable information including but not limited to:
            </p>
            <ul className="list-disc pl-6 space-y-2">
              <li>Email address</li>
              <li>First name and last name</li>
              <li>Phone number</li>
              <li>Usage Data</li>
            </ul>

            <h4 className="text-lg font-semibold">Usage Data</h4>
            <p>
              Usage Data is collected automatically and may include information
              such as Your IP address, browser type, version, pages visited,
              time and date of visit, time spent on pages, and other diagnostic
              data.
              <br></br>
              <br></br>
              Usage Data is collected automatically when using the Service.
              <br></br>
              <br></br>
              Usage Data may include information such as Your Device&apos;s Internet
              Protocol address (e.g. IP address), browser type, browser version,
              the pages of our Service that You visit, the time and date of Your
              visit, the time spent on those pages, unique device identifiers
              and other diagnostic data.
              <br></br>
              <br></br>
              When You access the Service by or through a mobile device, We may
              collect certain information automatically, including, but not
              limited to, the type of mobile device You use, Your mobile device
              unique ID, the IP address of Your mobile device, Your mobile
              operating system, the type of mobile Internet browser You use,
              unique device identifiers and other diagnostic data.
              <br></br>
              <br></br>
              We may also collect information that Your browser sends whenever
              You visit our Service or when You access the Service by or through
              a mobile device.
            </p>

            <h4 className="text-lg font-semibold">
              Tracking Technologies and Cookies
            </h4>
            <p>
              We use Cookies and similar tracking technologies to track the
              activity on Our Service and store certain information. Tracking
              technologies used are beacons, tags, and scripts to collect and
              track information and to improve and analyze Our Service. The
              technologies We use may include:
            </p>
            <ul className="list-disc pl-6 space-y-2">
              <li>
                <strong>Cookies or Browser Cookies:</strong> A cookie is a small
                file placed on Your Device. You can instruct Your browser to
                refuse all Cookies or to indicate when a Cookie is being sent.
                However, if You do not accept Cookies, You may not be able to
                use some parts of our Service. Unless you have adjusted Your
                browser setting so that it will refuse Cookies, our Service may
                use Cookies.
              </li>
              <li>
                <strong>Web Beacons:</strong> Certain sections of our Service
                and our emails may contain small electronic files known as web
                beacons (also referred to as clear gifs, pixel tags, and
                single-pixel gifs) that permit the Company, for example, to
                count users who have visited those pages or opened an email and
                for other related website statistics (for example, recording the
                popularity of a certain section and verifying system and server
                integrity).
              </li>
            </ul>

            <p>
              Cookies can be &quot;Persistent&quot; or &quot;Session&quot; Cookies. Persistent
              Cookies remain after going offline, while Session Cookies are
              deleted when You close Your browser.
            </p>

            <p>We use both Session and Persistent Cookies for the purposes set out below:</p>

            <ul className="list-disc pl-5 space-y-6">
              <li>
                <h3 className="text-lg font-bold mb-2">
                  Necessary / Essential Cookies
                </h3>
                <p>
                  <strong>Type:</strong> Session Cookies
                </p>
                <p>
                  <strong>Administered by:</strong> Us
                </p>
                <p>
                  <strong>Purpose:</strong> These Cookies are essential to
                  provide you with services available through the Website and to
                  enable you to use some of its features. They help to
                  authenticate users and prevent fraudulent use of user
                  accounts. Without these Cookies, the services that you have
                  asked for cannot be provided, and we only use these Cookies to
                  provide you with those services.
                </p>
              </li>

              <li>
                <h3 className="text-lg font-bold mb-2">
                  Cookies Policy / Notice Acceptance Cookies
                </h3>
                <p>
                  <strong>Type:</strong> Persistent Cookies
                </p>
                <p>
                  <strong>Administered by:</strong> Us
                </p>
                <p>
                  <strong>Purpose:</strong> These Cookies identify if users have
                  accepted the use of cookies on the Website.
                </p>
              </li>

              <li>
                <h3 className="text-lg font-bold mb-2">
                  Functionality Cookies
                </h3>
                <p>
                  <strong>Type:</strong> Persistent Cookies
                </p>
                <p>
                  <strong>Administered by:</strong> Us
                </p>
                <p>
                  <strong>Purpose:</strong> These Cookies allow us to remember
                  choices you make when you use the Website, such as remembering
                  your login details or language preference. The purpose of
                  these Cookies is to provide you with a more personal
                  experience and to avoid you having to re-enter your
                  preferences every time you use the Website.
                </p>
              </li>
            </ul>

            <p>For more information about the cookies we use and your choices regarding cookies, please visit our Cookies Policy or the Cookies section of our Privacy Policy.</p>

            <h3 className="text-xl font-semibold">Use of Your Personal Data</h3>
            <p>The Company may use Personal Data for the following purposes:</p>
            <ul className="list-disc pl-6 space-y-2">
              <li>To provide and maintain our Service</li>
              <li>To manage Your Account</li>
              <li>To perform a contract</li>
              <li>To contact You</li>
              <li>To provide You with news and offers</li>
              <li>To manage Your requests</li>
              <li>For business transfers</li>
              <li>For other analytical and service improvement purposes</li>
            </ul>

            <p>
              We may share Your information with Service Providers, Affiliates,
              business partners, or others with Your consent.
            </p>

            <h3 className="text-xl font-semibold">
              Retention of Your Personal Data
            </h3>
            <p>
              We will retain Your Personal Data only as long as necessary to
              fulfill purposes outlined in this policy, and to comply with legal
              obligations.
            </p>

            <h3 className="text-xl font-semibold">
              Transfer of Your Personal Data
            </h3>
            <p>
              Your information may be transferred to — and maintained on —
              computers outside of Your jurisdiction. We ensure data is treated
              securely.
            </p>

            <h3 className="text-xl font-semibold">Delete Your Personal Data</h3>
            <p>
              You may request deletion of Your Personal Data by contacting us or
              accessing Your account settings.
            </p>

            <h3 className="text-xl font-semibold">
              Disclosure of Your Personal Data
            </h3>
            <ul className="list-disc pl-6 space-y-2">
              <li>
                <strong>Business Transactions:</strong> In the event of a merger
                or sale.
              </li>
              <li>
                <strong>Law Enforcement:</strong> If required by law.
              </li>
              <li>
                <strong>Other Legal Requirements:</strong> To protect rights,
                safety, or comply with obligations.
              </li>
            </ul>

            <h3 className="text-xl font-semibold">
              Security of Your Personal Data
            </h3>
            <p>
              We strive to use commercially acceptable means to protect Your
              data but cannot guarantee absolute security.
            </p>

            <h2 className="text-2xl font-semibold">Children&apos;s Privacy</h2>
            <p>
              We do not knowingly collect information from anyone under the age
              of 13. If aware of such data, we take steps to delete it.
            </p>

            <h2 className="text-2xl font-semibold">Links to Other Websites</h2>
            <p>
              Our Service may contain links to external sites not operated by
              Us. We advise reviewing their privacy policies.
            </p>

            <h2 className="text-2xl font-semibold">
              Changes to this Privacy Policy
            </h2>
            <p>
              We may update our Privacy Policy from time to time and notify
              users by posting the new policy here.
            </p>

            <h2 className="text-2xl font-semibold">Contact Us</h2>
            <p>
              If you have any questions, you can contact us via email at{" "}
              <Link
                href="mailto:qurban.quliyev@brilliant-travel.com"
                className="underline"
              >
                qurban.quliyev@brilliant-travel.com
              </Link>
            </p>
          </section>
        </div>
      </main>
    </div>
  );
}
